[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Andrzej Swatowski"]
edition = "2018"
repository = "https://github.com/swtwsk/aoc2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"  # for Day 18
